services:
  redis_db:
    image: redis
    ports:
      - 6379:6379
    networks:
      - mail_net

  app:
    build:
      context: .
    depends_on:
      - redis_db
    ports:
      - 3000:3000
    environment:
      - server_address=app
      - server_port=3000
      - redis_address=redis_db
      - redis_port=6379
    networks:
      - mail_net

networks:
  mail_net: